//! Pipeline configuration (`pipeline.json`).
//!
//! Portable JSON document describing a complete pipeline:
//!
//!   * a single [`SourceConfig`] (camera, file, etc. — engine-shipped, not an
//!     addon),
//!   * an ordered list of [`NodeConfig`] entries (addon instances with their
//!     per-instance configuration), and
//!   * a single [`SinkConfig`] (window, recording, etc. — also engine-shipped).
//!
//! Each [`NodeConfig`] carries an `instance_id` so the same addon can appear
//! multiple times in a pipeline (duplicate, reorder, enable/disable) without
//! collisions. Edits flow through [`PipelineConfig`] mutators that preserve
//! that invariant.
//!
//! The format is intentionally JSON (not TOML): pipelines are
//! tooling-generated and tooling-consumed, JSON has better library coverage
//! and ordering semantics, and round-tripping through a UI is trivial.

use std::collections::HashSet;
use std::fs;
use std::path::Path;

use serde::{Deserialize, Serialize};

use super::error::{AddonError, Result};
use super::registry::AddonRegistry;
use super::schema::{ParamMap, ParamValue};

pub const CURRENT_PIPELINE_FORMAT: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PipelineConfig {
    pub format_version: u32,

    #[serde(default)]
    pub name: Option<String>,

    pub source: SourceConfig,

    #[serde(default)]
    pub pipeline: Vec<NodeConfig>,

    pub sink: SinkConfig,
}

/// Identifies an engine-shipped frame source (e.g. `"webcam"`, `"file"`,
/// `"screen"`). The string is interpreted by the engine's source registry;
/// this layer does not enumerate which sources exist.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceConfig {
    #[serde(rename = "type")]
    pub kind: String,
    #[serde(default = "default_config_object")]
    pub config: serde_json::Value,
}

/// Identifies an engine-shipped frame sink (e.g. `"window"`, `"recording"`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SinkConfig {
    #[serde(rename = "type")]
    pub kind: String,
    #[serde(default = "default_config_object")]
    pub config: serde_json::Value,
}

fn default_config_object() -> serde_json::Value {
    serde_json::Value::Object(serde_json::Map::new())
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeConfig {
    /// Unique within this pipeline. Generated by [`PipelineConfig::add_node`]
    /// and [`PipelineConfig::duplicate_node`]; preserved on save/load.
    pub instance_id: String,

    /// The `id` field of an installed addon's manifest.
    pub addon: String,

    #[serde(default = "default_enabled")]
    pub enabled: bool,

    #[serde(default)]
    pub config: ParamMap,
}

fn default_enabled() -> bool {
    true
}

/// A single problem detected when validating a pipeline against an
/// [`AddonRegistry`]. Validation never throws — it returns a list so the UI
/// can render every issue at once.
#[derive(Debug, Clone)]
pub struct PipelineIssue {
    pub node_index: usize,
    pub instance_id: String,
    pub kind: PipelineIssueKind,
}

#[derive(Debug, Clone)]
pub enum PipelineIssueKind {
    AddonNotInstalled { addon: String },
    UnknownParam { key: String },
    InvalidParam { key: String, reason: String },
}

impl std::fmt::Display for PipelineIssue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "node #{} ({}): ", self.node_index, self.instance_id)?;
        match &self.kind {
            PipelineIssueKind::AddonNotInstalled { addon } => {
                write!(f, "addon {addon:?} is not installed")
            }
            PipelineIssueKind::UnknownParam { key } => {
                write!(f, "unknown param {key:?}")
            }
            PipelineIssueKind::InvalidParam { key, reason } => {
                write!(f, "param {key:?}: {reason}")
            }
        }
    }
}

impl PipelineConfig {
    /// Create a fresh empty pipeline with the given source and sink.
    pub fn new(source: SourceConfig, sink: SinkConfig) -> Self {
        Self {
            format_version: CURRENT_PIPELINE_FORMAT,
            name: None,
            source,
            pipeline: Vec::new(),
            sink,
        }
    }

    pub fn load(path: &Path) -> Result<Self> {
        let bytes = fs::read_to_string(path)?;
        let config: PipelineConfig = serde_json::from_str(&bytes)?;
        config.validate_structure()?;
        Ok(config)
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        self.validate_structure()?;
        let bytes = serde_json::to_string_pretty(self)?;
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent)?;
            }
        }
        fs::write(path, bytes)?;
        Ok(())
    }

    /// Structural validation: format version + uniqueness of instance ids.
    /// Does not consult the registry — for that, use
    /// [`validate_against`](Self::validate_against).
    pub fn validate_structure(&self) -> Result<()> {
        if self.format_version != CURRENT_PIPELINE_FORMAT {
            return Err(AddonError::InvalidPipeline(format!(
                "unsupported format_version {} (this engine expects {})",
                self.format_version, CURRENT_PIPELINE_FORMAT
            )));
        }
        let mut ids = HashSet::new();
        for n in &self.pipeline {
            if n.instance_id.is_empty() {
                return Err(AddonError::InvalidPipeline(
                    "node has empty instance_id".into(),
                ));
            }
            if !ids.insert(n.instance_id.as_str()) {
                return Err(AddonError::InvalidPipeline(format!(
                    "duplicate instance_id {:?}",
                    n.instance_id
                )));
            }
        }
        if self.source.kind.is_empty() {
            return Err(AddonError::InvalidPipeline("source.type is empty".into()));
        }
        if self.sink.kind.is_empty() {
            return Err(AddonError::InvalidPipeline("sink.type is empty".into()));
        }
        Ok(())
    }

    /// Check that every referenced addon is installed and every config value
    /// matches its addon's [`ParamSpec`](super::schema::ParamSpec). Returns
    /// the list of issues; an empty list means the pipeline is loadable.
    pub fn validate_against(&self, registry: &AddonRegistry) -> Vec<PipelineIssue> {
        let mut issues = Vec::new();
        for (i, node) in self.pipeline.iter().enumerate() {
            let Some(entry) = registry.get(&node.addon) else {
                issues.push(PipelineIssue {
                    node_index: i,
                    instance_id: node.instance_id.clone(),
                    kind: PipelineIssueKind::AddonNotInstalled {
                        addon: node.addon.clone(),
                    },
                });
                continue;
            };
            for (key, value) in &node.config {
                let Some(spec) = entry.manifest.params.get(key) else {
                    issues.push(PipelineIssue {
                        node_index: i,
                        instance_id: node.instance_id.clone(),
                        kind: PipelineIssueKind::UnknownParam { key: key.clone() },
                    });
                    continue;
                };
                if let Err(reason) = spec.validate(value) {
                    issues.push(PipelineIssue {
                        node_index: i,
                        instance_id: node.instance_id.clone(),
                        kind: PipelineIssueKind::InvalidParam {
                            key: key.clone(),
                            reason,
                        },
                    });
                }
            }
        }
        issues
    }

    // ---- editing operations ----

    /// Insert a node referencing `addon_id`. If `at` is `Some(idx)` (in
    /// range), insert there; otherwise append. Returns the new instance id.
    pub fn add_node(&mut self, addon_id: &str, at: Option<usize>) -> String {
        let instance_id = new_instance_id();
        let node = NodeConfig {
            instance_id: instance_id.clone(),
            addon: addon_id.to_owned(),
            enabled: true,
            config: ParamMap::new(),
        };
        match at {
            Some(idx) if idx <= self.pipeline.len() => self.pipeline.insert(idx, node),
            _ => self.pipeline.push(node),
        }
        instance_id
    }

    pub fn remove_node(&mut self, instance_id: &str) -> bool {
        let before = self.pipeline.len();
        self.pipeline.retain(|n| n.instance_id != instance_id);
        self.pipeline.len() != before
    }

    /// Move the node with `instance_id` to position `to` (clamped to the
    /// current pipeline length).
    pub fn move_node(&mut self, instance_id: &str, to: usize) -> bool {
        let Some(from) = self.pipeline.iter().position(|n| n.instance_id == instance_id) else {
            return false;
        };
        let to = to.min(self.pipeline.len().saturating_sub(1));
        let node = self.pipeline.remove(from);
        self.pipeline.insert(to, node);
        true
    }

    /// Insert a clone of an existing node immediately after it. Returns the
    /// new instance id, or `None` if `instance_id` was not found.
    pub fn duplicate_node(&mut self, instance_id: &str) -> Option<String> {
        let idx = self
            .pipeline
            .iter()
            .position(|n| n.instance_id == instance_id)?;
        let mut copy = self.pipeline[idx].clone();
        copy.instance_id = new_instance_id();
        let new_id = copy.instance_id.clone();
        self.pipeline.insert(idx + 1, copy);
        Some(new_id)
    }

    pub fn set_enabled(&mut self, instance_id: &str, enabled: bool) -> bool {
        for n in &mut self.pipeline {
            if n.instance_id == instance_id {
                n.enabled = enabled;
                return true;
            }
        }
        false
    }

    pub fn set_param(&mut self, instance_id: &str, key: &str, value: ParamValue) -> bool {
        for n in &mut self.pipeline {
            if n.instance_id == instance_id {
                n.config.insert(key.to_owned(), value);
                return true;
            }
        }
        false
    }

    pub fn get_node(&self, instance_id: &str) -> Option<&NodeConfig> {
        self.pipeline.iter().find(|n| n.instance_id == instance_id)
    }
}

fn new_instance_id() -> String {
    nanoid::nanoid!(10, &nanoid::alphabet::SAFE)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn empty() -> PipelineConfig {
        PipelineConfig::new(
            SourceConfig {
                kind: "webcam".into(),
                config: default_config_object(),
            },
            SinkConfig {
                kind: "window".into(),
                config: default_config_object(),
            },
        )
    }

    #[test]
    fn add_and_remove() {
        let mut p = empty();
        let a = p.add_node("io.test.a", None);
        let b = p.add_node("io.test.b", None);
        assert_eq!(p.pipeline.len(), 2);
        assert!(p.remove_node(&a));
        assert_eq!(p.pipeline.len(), 1);
        assert_eq!(p.pipeline[0].instance_id, b);
    }

    #[test]
    fn duplicate_assigns_new_id() {
        let mut p = empty();
        let a = p.add_node("io.test.a", None);
        let dup = p.duplicate_node(&a).expect("dup");
        assert_ne!(a, dup);
        assert_eq!(p.pipeline.len(), 2);
        assert_eq!(p.pipeline[0].addon, p.pipeline[1].addon);
    }

    #[test]
    fn move_reorders() {
        let mut p = empty();
        let a = p.add_node("io.test.a", None);
        let b = p.add_node("io.test.b", None);
        let c = p.add_node("io.test.c", None);
        // [a, b, c] → move c to 0 → [c, a, b]
        assert!(p.move_node(&c, 0));
        assert_eq!(p.pipeline[0].instance_id, c);
        assert_eq!(p.pipeline[1].instance_id, a);
        assert_eq!(p.pipeline[2].instance_id, b);
    }

    #[test]
    fn set_enabled_and_param() {
        let mut p = empty();
        let a = p.add_node("io.test.a", None);
        assert!(p.set_enabled(&a, false));
        assert!(!p.get_node(&a).unwrap().enabled);
        assert!(p.set_param(&a, "intensity", ParamValue::F32(0.5)));
        assert_eq!(
            p.get_node(&a).unwrap().config.get("intensity"),
            Some(&ParamValue::F32(0.5))
        );
    }

    #[test]
    fn structure_validation_catches_duplicate_ids() {
        let mut p = empty();
        let _a = p.add_node("io.test.a", None);
        // Forge a collision.
        let dup = p.pipeline[0].clone();
        p.pipeline.push(dup);
        assert!(p.validate_structure().is_err());
    }

    #[test]
    fn round_trip_through_json() {
        let mut p = empty();
        p.name = Some("test".into());
        let a = p.add_node("io.test.a", None);
        p.set_param(&a, "x", ParamValue::F32(1.5));
        p.set_param(&a, "y", ParamValue::Str("hi".into()));

        let json = serde_json::to_string(&p).unwrap();
        let back: PipelineConfig = serde_json::from_str(&json).unwrap();
        back.validate_structure().unwrap();
        assert_eq!(back.pipeline.len(), 1);
        assert_eq!(back.pipeline[0].config.len(), 2);
    }
}
